<!DOCTYPE html>
<html lang="lt">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kaip nesuklysti renkantis vestuvių fotografą | Kronos Portraits</title>
    <link rel="stylesheet" href="/css/styles.css">
</head>
<body>
    <?php include 'header.html'; ?>
    <main>
        <h1>7 išsamūs patarimai kaip nesuklysti renkantis vestuvių fotografą</h1>
        <article class="article-container">
            <p class="blog-article-paragraph">Įvairių apklausų duomenimis vestuvių fotografai patenka tarp TOP 5 pirmiausia pasirenkamų vestuvinių paslaugų tiekėjų kartu su vestuvių planuotoja, ceremonijos vieta, šventės vieta ir vestuvių vedėju (DJ, grupe). Nuo šito penketuko rezervacijų ir reikėtų pradėti planuojant savo vestuves, kadangi geriausių savo srities specialistų darbų sąrašas neretai būna pildomas metams į priekį, o suskubę anksčiau turi didesnę galimybę susirinkti savo svajonių komandą. Kalbant apie fotografo vestuvėms pasirinkimą turiu Jums dvi žinias: geroji žinia yra ta, kad jų yra tikrai daug, o blogoji – tai nepadaro Jūsų pasirinkimo lengvesniu, nes vis tiek reikia atlikti namų darbus. Gali būti jog ne visi patarimai Jums bus aktualūs ar pritaikomi, bet šiuo atveju manome, kad geriau žinoti daugiau nei praleisti kokią detalę, kuri gali įtakoti galutinį rezultatą. Tai visgi, į ką reikia atsižvelgti renkantis vestuvių fotografą:
            </p>
            <ol>
                <li><img src="../images/tinklarastis/issamus_patarimai_kaip_nesuklysti_renkantis_vestuviu_fotografa.JPG" alt="Jaunasis ir jaunoji" class="inside-article-image-right">
                    <strong>Kur ieškoti ir į ką atkreipti dėmesį?</strong> Paprasčiausias ir greičiausias būdas be jokios abejonės yra paieška Google arba Facebook. Toliau seka įvairūs specializuoti vestuvinių paslaugų tinklapiai, kitų vestuvinių paslaugų teikėjų rekomendacijos, draugų ir pažystamų rekomendacijos. Gali būti, jog, kur nors būsite perskaitę, kad rekomendacijomis remtis neverta, nes, kas patinka Jūsų draugams, nebūtinai patiks Jums, bet jei mano draugai papasakotų kaip džiaugėsi savo fotografu ir kaip dėl savo klientų jis padarė kažką ekstra, ko iš jo galbūt net nebuvo tikimąsi, tai man signalizuotų puikų klientų aptarnavimą ir reikštų, kad šis fotografas tikrai rimtai žiūri į savo darbą. Tačiau vien tuo žinoma nereikia apsiriboti, reikia įsivertinti ar jis atitiks ir kitus pasirinkimo kriterijus. Paieškai skirkite laiko, bet atradę 3-5 Jums patinkančius galite pradėti atsirinkinėti atsižvelgdami į kitus patarimus. Paieškokite Google ir atsiliepimų apie Jūsų pasirinktus fotografus, jei fotografas dirba seniai gali būti, jog kur nors rasite paliktų atsiliepimų, bet turėkite omeny, kad žmonės daug dažniau paliks neigiamą atsiliepimą, negu teigiamą. Radus kažką neigiamo vėlgi reiktų įsivertinti ar tai buvo seniai parašyta ir ar tas neigiamas aspektas jums svarbus. Jei klientams netiko nuotraukų spalva tai gal nebus Jums taip svarbu kaip kad jo bendravimas ir elgesys. Fotografas taip pat gali turėti atsiliepimų skyrelį savo internetiniame arba Facebook puslapyje, o jei tokio nėra, galite paprašyti buvusių klientų kontaktų, bet šiuo atveju natūralu, kad fotografas turės atsiklausti savo klientų ir gerbti Jų norą jei šie atsisakytų, nors mūsų patirtis rodo, kad taip būna tikrai retai.
                </li>
                <li>
                    <strong>Pasirinkite fotografą, kurio nuotraukos iš tikrųjų patinka</strong>. Šitas toks kaip ir akivaizdus punktas, nes kodėl gi samdome fotografą jei ne dėl patinkančių nuotraukų, ogi kaip būna meilė iš išskaičiavimo, taip ir fotografas būna pasirenkamas dėl kainos, bet apie kainą bus atskiras punktas, o šiame patarimas peržiūrėti fotografo darytas kelių vestuvių visos dienos nuotraukas. Kai kurie fotografai sukelia visas arba didžiąją dalį vestuvių nuotraukų į savo internetinį arba Facebook puslapį, kiti apsiriboja tik geriausiais rinktiniais kadrais. Kurias ir kiek nuotraukų įsideda fotografas yra jo asmeninis pasirinkimas, tačiau peržiūrėję visas kelių vestuvių nuotraukas pamatysite ar Jums patinka bendras vaizdas, ar fotografas sugeba fotografuot naktinę dalį, kuomet mažai šviesos ir reikalinga turėti ir išmanyti papildomus šviesos šaltinius, ar galų gale gerosios nuotraukos nėra padarytos seminaro metu su meistro priežiūra, o kartais ir nugvelbtos iš kito fotografo.
                </li>
                <li>
                    <strong>Nuspręskite koks fotografo darbo stilius Jums priimtinas</strong>. Vienas iš dalykų, dėl kurio reikia apsispręsti renkantis fotografą, tai jo darbo stilius. Kalbant apie vestuvių fotografiją dažniausiai pasitaikantys fotografavimo stiliai: reportažinis, pastatyminis arba abiejų ankstesnių mišinys.  Apie kiekvieną jų plačiau:
                    <ol type="a">
                        <li>Reportažinį stilių propaguojantys fotografai leidžia šventei tekėti sava vaga ir visiškai nesikiša į įvykių eigą. Toks stilius labiausiai tinka žmonėms kurie, mėgsta nenugludintą natūralumą, nemėgsta pozuoti ir kurie nusiteikę aktyviai švęsti (jodinėjimas žirgais, degustacija, įvairūs žaidimai). Tačiau šis stilius netiks žmonėms, kuriem reikia bent šiokių tokių patarimų, pvz., kaip atsistoti, kur padėti rankas ir kur žiūrėti. Greičiausiai vienintelės minimaliai pozuotos nuotraukos bus iš sveikinimų dalies.</li>
                        <li>Pastatyminis stilius dar gali būti skirstomas į tradicinį, meninį ir mados, bet apibūdinant bendrai, tai šiuo atveju fotografas padeda jauniesiems parinkdamas vietą, pozą ar veiksmus, tam, kad būtų kuo gražiau papasakota Jūsų vestuvių istoriją. Šio stiliaus fotografas nesulaukdamas „WOW“ momento gali jį sukurti pasinaudodamas aplinka, šviesa ir galybe kitų būdų. Tai reportažiniui visiškai priešingas fotografavimo stilius, kuriame nepozuotos nuotraukos dažniausiai būna tik iš ceremonijos ir naktinės dalies.</li>
                        <li>Abiejų ankstesnių mišinys – kuomet atsižvelgiant į situaciją naudojamas vienas ar kitas stilius taip išnaudojant abiejų stilių privalumus. Gali būti, kad vienas fotografas bus įvaldęs abu fotografavimo stilius, bet galimas sprendimas kuomet du skirtingų stilių fotografai dirba poroje.</li>
                    </ol>
                    Nė vienas iš stilių nėra geresnis ar blogesnis, bet nuo jo priklausys kaip jaukiai jausitės su fotografu, o tai atsispindės ir nuotraukose.
                </li>
                <li>
                    Nuotraukos ir stilius patinka. Mūsų data laisva. Imam? Dar šiek tiek palūkėkit. Vestuvių fotografas, tai žmogus su kuriuo bendrausite iki vestuvių, visą dieną per vestuves, ir žinoma po vestuvių iki Jums bus įteikta Jūsų nuotraukos ir albumas, tad jis bus ne tik žmogus fiksuojantis atsiminimus bet ir didelė jų dalis. Tokiu atveju tikrai nenorėtumėt turėt erzinančio, grubaus, pasipūtusio ar laidančio netinkamus juokelius asmens šalia savęs. Kažin ar prie tokio asmens galėsite atsipalaiduoti, o nuotraukose ir atsiminimuose viskas liks. Taigi, šiuo atveju <strong>mūsų patarimas būtų jauniesiems susitikti su fotografu ir pabendrauti gyvai</strong>. Pabendravę suprasite ar sutampa idėjos, požiūriai ir auros &#128522; Jei ne, ieškokite kito fotografo. O jeigu fotografo asmenybė ir bendravimas Jums patinka, ir jei laikas bei finansai leidžia, galite atlikti bandomąją/“love story“ fotosesiją, kurioje pamatysite kaip fotografas dirba. Kraštutiniu atveju, jeigu gyvai susitikti neįmanoma, nes galbūt gyvenate užsienyje ir iki vestuvių neparvyksite, pasinaudokite šiuolaikinių technologijų teikiamais privalumais ir susitarkite dėl pokalbio telefonu ar dar geriau Skype vaizdo skambučiu.
                </li>
                <li>
                    <strong>Kaip išmatuoti patirtį?</strong> Daugelis turi pusbrolį ar draugę, kurie turi gerą fotoaparatą ir labai gražiai fotografuoja savo kačiukus ir gamtą, kodėl gi nepaėmus jų už vestuvių fotografą? Argumentų prieš tikrai ne vienas:
                    <ol type="a">
                        <li>Jei tai tikrai artimas pusbrolis ar draugė, geriau jau leiskite jiems atsipalaiduoti ir švęsti kartu su Jumis;</li>
                        <li>Jūs tikrai nežinote iš keliasdešimt ar kelių šimtų kadrų gavosi ta viena graži kačiuko nuotrauka, o vestuvėse tikrai ne vienas epizodas kurio nepakartosi;</li>
                        <li>Nepatyrusio fotografo įranga nebus pritaikyta sąlygoms kuomet yra mažai šviesos, neturės apsaugos lietaus atveju, taipogi jis greičiausiai neturės atsarginio fotoaparato, o įranga, kaip bebūtų gaila, bet genda ir laiko tam nesirenka.</li>
                    </ol>
                    Tuo tarpu patyręs vestuvių fotografas:
                    <ol type="a">
                        <li>Gerai žinos vestuvių tradicijas, ceremonijos eigą santuokų rūmuose ar bažnyčioje, turės vakarinės dalies scenarijų ir nebus išėjęs pailsėti nes nėra pratęs prie tokio krūvio ir įtampos;</li>
                        <li>Gali atstoti vestuvių planuotoją ar koordinatorę planuojant dienos įvykius ir jiems skirtą laiką, patarti ir rekomenduoti kitus vestuvių paslaugų tiekėjus;</li>
                        <li>Tai yra pirmasis žmogus kurio reiktų klausti dėl vietų ir idėjų fotosesijoms, o net ir kasdieninėse ar niekuo neišsiskiriančiose vietose jis gali sukurti nekasdieniškas nuotraukas pasitelkdamas šviesą, Jūsų emocijas ir kompozicinius sprendimus;</li>
                        <li>Turės visą reikalingą fotografavimui įrangą, tame tarpe ir atsarginę;</li>
                        <li>Galų gale turės „vestuvių išgyvenimo rinkinį“ kur bus paruoštas pleistras jei Jums pritrintų koją ar siūlo su adata nelaiku ištrūkusiai sagai įsiūti.</li>
                    </ol>
                    Taigi, kaip pamatuoti tą patirtį? Peržvelkite ar fotografas savo puslapyje turi daug skirtingų vestuvių nuotraukų ar dauguma nuotraukų iš kelių vestuvių. Paklauskite kiek metų fotografuoja vestuves ir kiek vestuvių per metus, nors yra fotografų, kurie norėdami kuo geriau aptarnauti savo klientus riboja per metus fotografuojamų vestuvių skaičių, bet vis tiek bent apytikslį vaizdą susidaryti galėsite. Taipogi aptarkite fotografavimosi vietas, idėjas ir ką darysite jei lis, jei atsakymai į šiuos klausimus Jūsų netenkina, svarstysite kitą kandidatą. Tačiau vienareikšmio patarimo ties šiuo punktu nėra, visi tobulėja skirtingai ir pradeda fotografuoti vestuves būdami ne vienodo lygio, tad nebūtina ieškoti fotografo su 20 metų fotografavimo patirtimi, nes ir dvejus trejus metus vestuves fotografavę fotografai gali būti sukaupę pakankamai patirties ir lenkt 50mečius kolegas, kurie vis dar klijuoja gulbes į nuotraukas ar fotografuoja jaunikį ant delno „laikantį“ nuotaką &#128522;
                </li>
                <li>
                    <strong>Kaina</strong>. Pažadu, kad detalus straipsnis, kodėl vestuvių fotografas negali kainuoti pigiai bus ateityje, o dabar trumpai ir drūtai, geras vestuvių fotografas kainuoja daug, nes kainą apsprendžia ne tik nuotraukų grožis, bet ir pasirinkta kainodara, patirtis, tobulėjimo kursai, technika, programinė įranga, aptarnavimas ir N kitų dalykų skirtų, kad galutinis rezultatas Jus džiugintų. Įsivaizduokite, kad už nebrangiai dirbančiam fotografui savaitę iki Jūsų vestuvių sugedo fotoaparatas. Ar jis galės Jūsų vestuvėms nusipirkti naują, kuomet pusiau profesionalaus fotoaparato kaina prasideda virš 1000e., o ką jau kalbėt apie profesionalią įrangą. Dar lieka galimybė nuomotis, bet sezono metu dažnai visa įranga būna užsakyta gerokai iš anksto, arba skolintis iš kolegos, bet o jei kolega irgi turi vestuves? Tiesa, geras fotografas gali kainuoti pigiau jei vestuves kelsite ne sezono metu (lapkričio-balandžio mėnesiais), arba sezono metu bet darbo dienomis. Jei šie variantai ne Jums kainą susimažinti dar gali padėti vestuvių dienos įvykių planavimas taip kad jie užimtų ne 12 val. o tik 10 ar 8 val. Dar vienas aspektas, kad fotografo kaina metų bėgyje gali keistis, vieni artėjant sezonui ir daugėjant užsakymų kaip ir koncertų organizatoriai ima ir kainą pakelia, kiti neturint pakankamai užsakymų prieš sezoną kainą kiek pamažina, bet vis tik dažniausiai galioja taisyklė, jog laimi tie, kurie rezervuojasi fotografą anksčiau.
                <li>
                    <strong>Fotografas atrodo patikimas, gal užteks tik sukirst rankom?</strong> Vienas iš punktų, kuris gali smarkiai apkartinti patirtį su fotografu yra aplaidus požiūris į sutarties pasirašymą. Sutartis neišsprendžia tik meninės nuotraukų išraiškos, bet visi kiti aspektai tokie kaip fotografavimo laikas, kaina, atliekamos paslaugos ir jų terminai, kas bus jei fotografas susirgtų ir negalėtų atvykti į vestuves ir daug daug kitų dalykų. Kiek detali turi būti sutartis? Manau, kad kuo detalesnė tuo mažiau nesusikalbėjimų ir nesusipratimų bus ateityje. Jeigu laikui bėgant norite pakeisti ar papildyti sutartį nauja informacija pvz. nusprendėte, kad jaunieji ruošis skirtingose vietose, o sutartyje buvo numatyta, kad toje pačioje, neapsiribokite pranešdami informaciją telefonu, bet parašykite ir el. paštu taip būsite tikri, kad informacija pasiekė gavėją ir atmintis neiškrės jokių pokštų.
                </li>
            </ol>
            <p class="blog-article-paragraph"><strong>Pabaigai</strong>. Jeigu jau tvirtai nusprendėte rezervuoti fotografą, darykite tai iškarto. Tai paprastai reiškia, kad fotografui sumokami rankpinigiai ir patvirtinama sutartis. Labai išimtinais atvejais fotografai apsiima palaikyti datą be šių garantijų, o tai, kad prieš mėnesį šnekėjot, bet nepatvirtinot savo sprendimo, nieko nereiškia, kadangi šiuo atveju pirmas rezervavęs pirmas ir aptarnaujamas.
            </p>
            <p class="blog-article-paragraph">Sėkmės renkantis ir gražių Jums šventės akimirkų!</p>
            <p class="blog-article-paragraph">P.S. Visas mūsų naujienas greičiausiai sužinosite sekdami <a href="https://www.facebook.com/KronosPortraits/" target="_blank">mūsų Facebook paskyrą</a>. Jei turit klausimų, pasiūlymų naujiems straipsniams ar norite pasidalinti savo patirtimi ar įžvalgomis nesikuklinkite ir susisiekite su mumis <a href="kontaktai.php">čia</a>.
            </p>
        </article>
    </main>
    <?php include 'footer.html'; ?>
</body>
</html>
